{{ if .Values.smtplogger.deploy }}
{{- $cpu := dict "XS" "10m" "S" "10m" "M" "10m" "L" "10m" "XL" "10m" "XXL" "10m" }}
{{- $mem := dict "XS" "50Mi" "S" "50Mi" "M" "50Mi" "L" "50Mi" "XL" "50Mi" "XXL" "50Mi" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smtplogger
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: Recreate
  template:
    metadata:
      name: smtplogger
      labels:
        app: smtplogger
    spec:
      containers:
        - name: smtplogger
          image: {{ .Values.smtplogger.image }}
          resources:
            requests:
              cpu: {{ get $cpu .Values.resourceSizing }}
              memory: {{ get $mem .Values.resourceSizing }}
            limits:
              cpu: {{ get $cpu .Values.resourceSizing }}
              memory: {{ get $mem .Values.resourceSizing }}
          ports:
            - name: smtp
              containerPort: 2500
  selector:
    matchLabels:
      app: smtplogger
{{ end }}
