version: '3'
services:
  cypress:
    image: "me/cypress"
    container_name: cypress
    command: ["/bin/sh", "-c", '/wait && /app/scripts/TestDatabaseSetup.sh http://nuxeo-backend:8080 && npm run cy:trashCopy && npm run cy:copy && cypress run --browser chrome --record true --headless --tag "AWS-server-test"']
    volumes:
      - '${PWD}/../frontend/cypress/videos:/app/cypress/videos'
      - '${PWD}/../frontend/cypress/screenshots:/app/cypress/screenshots'
    depends_on:
      - frontend
      - nuxeo-backend
      - elasticsearch
    environment:
      - WAIT_HOSTS=frontend:80, nuxeo-backend:8080, elasticsearch:9200
      - WAIT_SLEEP_INTERVAL=15
      - WAIT_AFTER_HOSTS=15
      - WAIT_HOSTS_TIMEOUT=120
      - CYPRESS_FV_USERNAME
      - CYPRESS_FV_PASSWORD
      - CYPRESS_PROJECT_ID
      - CYPRESS_RECORD_KEY