name: EKS Deploy (dev)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:

      - name: Cache skaffold cache
        id: cache-skaffold
        uses: actions/cache@v1.1.2
        with:
          path: ~/.cache
          key: ${{ runner.os }}-${{ hashFiles('**/skaffold.yaml') }}

      - name: Install skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          sudo install skaffold /usr/local/bin/

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/master/scripts/get-helm-3 | bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Hydrate kubeconfig
        env:
          CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        run: |
          mkdir $HOME/.kube
          echo -n "$CONFIG_DATA" | base64 -d > $HOME/.kube/config

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install kubectl /usr/local/bin/
          echo "version:"
          kubectl version
          echo "verifying kube connectivity"
          kubectl get nodes

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Checkout the current working code base
      - name: Checkout working branch
        uses: actions/checkout@v2

      - name: Build and Deploy
        run: |
          cd skaffold
          source awsdev.env
          skaffold deploy
