name: EKS Deploy (dev)

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:

      - name: skaffold cache
        id: cache-skaffold
        uses: actions/cache@v1.1.2
        with:
          path: ~/.skaffold
          key: ${{ runner.os }}-skaffoldcache

      - name: Install skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          sudo install skaffold /usr/local/bin/

      - name: Install Helm
        run: |
          curl -LO https://get.helm.sh/helm-v3.6.2-linux-amd64.tar.gz
          tar xzvf helm-v3.6.2-linux-amd64.tar.gz
          sudo install linux-amd64/helm /usr/local/bin

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-duration-seconds: 14400
          role-session-name: github-action

      - name: Hydrate kubeconfig
        env:
          CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
        run: |
          mkdir $HOME/.kube
          echo -n "$CONFIG_DATA" | base64 -d > $HOME/.kube/config
          chmod 0400 $HOME/.kube/config

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install kubectl /usr/local/bin/
          echo "version:"
          kubectl version

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and Deploy
        run: |
          cd skaffold
          source awsdev.env
          skaffold run
